name: Java CI

on: [push]

jobs:
  build:
    

    runs-on: ubuntu-latest
    
          
     
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Scipt File
      run: source './project.sh'
    - name: start mysql
      run: sudo service mysql start
    - name: Install Angular
      run: npm install -g @angular/cli@7.3.5
    - name: Create db
      run: mysql -uroot -proot -e "CREATE DATABASE movie_database;"
    - name: Build with Maven
      run: mvn install package
    - name: docker-login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build docker image
      run : docker-compose build
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v3.1.0
